version: 2

project_name: stonewall

builds:
  - env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags: -s -w -X main.version={{ .Version }}

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    artifacts: checksum
