version: 2

project_name: stonewall

builds:
  - env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags: -s -w -X main.version={{ .Version }}

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --yes
      - --output-certificate=${certificate}
      - --output-signature=${signature}
      - ${artifact}
    artifacts: checksum
